/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : MyHeaders.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2013-Sep 9, 2013, 7:16:58 PM, # CodeGen: 0
 **     Author	    : Dong
 **     Abstract    :
 **          This file contains all header files created by user.
 **          Easy for including header files in other files.
 **
 **     Mail      	: pzdongdong@163.com
 **
 **     Revision    : No.  Name        Data/Time        Content
 ** ###################################################################*/
/*!
 * @file MyHeaders.h
 * @version 01.00
 * @brief
 *		This file contains all header files created by user. Easy for including header files in other files.
 */
/*!
 *  @addtogroup MyHeaders My Headers
 *      This module contains all header files created by user. Easy for including header files in other files.
 *  @{
 */

#ifndef MYHEADERS_H_
#define MYHEADERS_H_
/* MODULE MYHEADERS */

#include "Settings.h"
#include "Macros.h"
#include "Globals.h"
#include "Aliases.h"
#include "ADC.h"
#include "Init.h"
#include "Process.h"
#if DEBUG
#include "Test.h"
#endif
#include "Utilities.h"
#include "SPI.h"
#include "Events.h"

//#include "SPI_PDD.h"

    /* END MODULE MYHEADERS. */

#endif
/* MYHEADERS_H_ */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */


