/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : Settings.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Datasheet   :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2013-Jul 17, 2013, 12:59:01 PM, # CodeGen: 1
 **     Author	    : Dong
 **     Abstract    :
 **			This file contains device and environment settings.
 **     Settings    :
 **
 **     Contents    :
 **
 **     Mail      	: pzdongdong@163.com
 **
 **     Revision    : No.  Name        Data/Time        Content
 ** ###################################################################*/
/*!
 * @file Settings.h
 * @version 01.00
 * @brief
 *      This file contains device and environment settings.
 */
/*!
 * @addtogroup DevEnvSet Device and Environment Settings
 *     This module contains device and environment settings.
 * @{
 */

#ifndef SETTINGS_H_
#define SETTINGS_H_
/* Module Settings */

    /*
     * ===================================================================
     * Others
     * ===================================================================
     */
    /*!
     * @addtogroup Oth Others
     * @{
     */
#define DEBUG 0     /*!< Debug mode. */
    /*!
     ** @}
     */

    /*
     * ===================================================================
     * Device In Use
     * ===================================================================
     */
    /*!
     * @addtogroup DevUse Device In Use
     * @{
     */
#define USING_MKL15Z128VLH4 1       /*!< MCU - Freescale MKL15Z128VLH4  */
#define USING_ADS1198       1       /*!< ADC - TI ADS1198 */
    /*!
     * @}
     */

    /*
     * ===================================================================
     * Component Switch - Decide what component will be used
     * ===================================================================
     */
    /*!
     * @addtogroup CmpSw Component Switch
     * @{
     */
#define USING_DMA      1    /*!< DMA controller will be used. */
#define USING_SPI0     1    /*!< SPI0 will be used. */
#define USING_SPI1     1    /*!< SPI1 will be used. */
#define USING_SPI0_DMA 1    /*!< SPI0 DMA TX & RX enabled. */
#define USING_SPI1_DMA 1    /*!< SPI1 DMA TX & RX enabled. */
#define USING_UART0    0    /*!< UART0 will not be used. */
#define USING_UART1    0    /*!< UART1 will not be used. */
#define USING_UART2    0    /*!< UART1 will not be used. */
    /*!
     * @}
     */

    /*
     * ===================================================================
     * Component Parameters - The parameters of Component settings
     * ===================================================================
     */
    /*!
     * @addtogroup CmpPara Component Parameters
     * @{
     */
#define PROCESSOR_CLOCK_48MHZ 1 /*!< Processor clock frequency is 48MHz. */
    /*!
     * @}
     */

    /* End Settings */

#endif
/* SETTINGS_H_ */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */

