/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : Test.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Datasheet   :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2013-07-12, 23:38, # CodeGen: 0
 **     Author	    : Dong
 **     Abstract    :
 **			This file contains test functions.
 **     Settings    :
 **
 **     Contents    :
 **         GPIO    - void GPIOTest(void);
 **
 **     Mail      	: pzdongdong@163.com
 **
 **     Revision    : No.  Name        Date/Time        Content
 ** ###################################################################*/
/*!
 * @file Test.h
 * @version 01.00
 * @brief
 *      This file contains test functions.
 */
/*!
 *  @addtogroup Test_module Test module documentation
 *      This module contains test functions.
 *  @{
 */

/* MODULE Test. */

#ifndef TEST_H_
#define TEST_H_


/* MODULE Test. */

/* {Default RTOS Adapter} No RTOS includes */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * ===================================================================
 *     Method      :  GPIOTest (Component GPIO)
 */
/*!
 *     @brief
 *          Test and output GPIO level via UART.
 */
/* ===================================================================*/
void GPIOTest(void);

/* END Test. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif
/* TEST_H_ */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */

